---
# tasks file for role
#
- name: Concatenate the public keys into string
  ansible.builtin.set_fact:
     ssh_keys_root_string: "{{ rootuser.ssh.authkeys | join('\n') }}"
  tags: [root,ssh]

- name: Manage the /root/.ssh/authorized_keys file roots authorized keys
  ansible.posix.authorized_key:
    user: root
    state: present
    key: '{{ ssh_keys_root_string }}'
    exclusive: "{{ rootuser.enforce_ssh }}"
  tags: [root,ssh]

- name: Generate ssh key for the root user
  ansible.builtin.user:
    name: root
    generate_ssh_key: yes
    ssh_key_bits: "{{ rootuser.ssh.keybits }}"
    ssh_key_type: "{{ rootuser.ssh.keytype }}"
  when: rootuser.ssh.genkey is defined and rootuser.ssh.genkey == true
  tags: [root,ssh]

- name: Set the root users password
  ansible.builtin.user:
    name: root
    password: "{{ rootuser.pass }}"
    update_password: always
  when: rootuser.enforce_pass is defined and rootuser.enforce_pass == true
  tags: [root,password]
